# Generated by Django 4.2 on 2023-05-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='ChatSet',
        ),
        migrations.RemoveField(
            model_name='question',
            name='create_date',
        ),
        migrations.DeleteModel(
            name='ChatSet',
        ),
    ]
